# Generated by Django 3.2.8 on 2021-11-06 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('questions', models.JSONField()),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.JSONField()),
                ('result_agricultura', models.IntegerField()),
                ('result_educacao', models.IntegerField()),
                ('result_ambiente', models.IntegerField()),
                ('result_saude', models.IntegerField()),
                ('result_infraestrutura', models.IntegerField()),
                ('result_desenvolvimento', models.IntegerField()),
                ('result_bancoCentral', models.IntegerField()),
                ('result_economia', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
