# Generated by Django 3.2.8 on 2021-11-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20211108_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='coup',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
