version: "3"

services:
  sensata-django:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: sensata-django
    env_file: .env
    volumes:
      - "./src/:/${APP_NAME}"
      - "./models/:/${APP_NAME}/models/"
    ports:
      - "8000:8000"
    networks:
      - default
