# Generated by Django 3.2.8 on 2021-11-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bloc',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Bloc',
        ),
    ]
