# Generated by Django 3.2.8 on 2021-11-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20211108_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.CharField(default='1000000000000', max_length=100),
        ),
    ]
